GET http://localhost:8888/auth/payco/oauth
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhY2Nlc3MtdG9rZW4iLCJtZW1iZXJJZCI6ImFkbWluIiwicm9sZXMiOlt7ImF1dGhvcml0eSI6IlJPTEVfQURNSU4ifSx7ImF1dGhvcml0eSI6IlJPTEVfQURNSU4xIn1dLCJpYXQiOjE3MTIxMzA1MjUsImV4cCI6MTcxMjEzNDEyNX0.LAyPs1ff_H4806PmFEeGoOcYkD3sK3gsv5Vpur4esAc


###
