GET http://localhost:8888/api/account/organizations
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiZXhwIjo1MDE2MjM5MDIyfQ.Mgyr4d8tKSVNTfiRCjfLGD8fQGMRF_hamYuZ-XopoYg



###
